### PR TITLE
Armk/selenium3 backward com

### LINKED ISSUE #724: Selenium v3 can no longer be started, error " Was passed main parameter '-I' but no main parameter was defined in your arg class"
## Expected Behavior
Selenium v3 should start normally.

## Current Behavior
```
$ selenium-standalone start --version=3.141.59
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-I' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at org.openqa.grid.selenium.GridLauncherV3.parse(GridLauncherV3.java:218)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$buildLaunchers$3(GridLauncherV3.java:241)
        at org.openqa.grid.selenium.GridLauncherV3.lambda$launch$0(GridLauncherV3.java:86)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:86)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:70)
/home/marco/test-selenium/node_modules/selenium-standalone/lib/check-started.js:44
      throw new Error(
            ^

Error: Selenium exited before it could start with code 1
Stdout:
Stderr:
    at checkStarted (/home/marco/test-selenium/node_modules/selenium-standalone/lib/check-started.js:44:13)
    at async Object.start (/home/marco/test-selenium/node_modules/selenium-standalone/lib/start.js:150:3)
    at async Object.start (/home/marco/test-selenium/node_modules/selenium-standalone/bin/selenium-standalone:23:16)
```

Running with `DEBUG=selenium-standalone:*` reveals the command that is executed:
```
 selenium-standalone:start Spawning Selenium Server process /usr/bin/java [
  '-Dwebdriver.chrome.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/chromedriver/latest-x64/chromedriver',
  '-Dwebdriver.gecko.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64/geckodriver',
  '-Dwebdriver.edge.driver=/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/chromiumedgedriver/latest-x64/msedgedriver',
  '-jar',
  '/home/marco/test-selenium/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59/selenium-server.jar',
  '-I',
  'chrome',
  '-I',
  'firefox',
  '-I',
  'edge'
]
```

## Steps to Reproduce

```
selenium-standalone install --version=3.141.59
selenium-standalone start --version=3.141.59
```

## Analysis

This regression is introduced since: https://github.com/webdriverio/selenium-standalone/pull/670 
Selenium v3 does not seem to support the `-I` option which was added in this PR.

@eric1234 Perhaps the blocks of code like: https://github.com/webdriverio/selenium-standalone/blob/main/lib/start.js#L89-L93
```
args.push('-Dwebdriver.chrome.driver=' + fsPaths.chrome.installPath);
opts.seleniumArgs.push('-I');
opts.seleniumArgs.push('chrome');
```

Should have been written like this?

```
args.push('-Dwebdriver.chrome.driver=' + fsPaths.chrome.installPath);
if (isSelenium4(opts.version)) {
  opts.seleniumArgs.push('-I');
  opts.seleniumArgs.push('chrome');
}
```

### PR DESCRIPTION
**Pull request by ArminazK**
fixes  #724 
problems:
* tests had hardcoded selenium 4 version, so no selenium3 tests were executed
* PR #670 added some code only selenium4 compatible
this PR fixes:
* npm script to run on both versions
* added `if isSelenium4...` for 670 PR changes
*  refactored `test/programmatic.js` to work with selenium3 and 4 (used old method for v3 and new for v4)

### CODE REVIEW

File: lib/default-config.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 module.exports = () => {
   const config = {
     baseURL: 'https://github.com/SeleniumHQ/selenium/releases/download',
-    version: '4.0.0',
+    version: process.env.SELENIUM_VERSION || '4.4.0',
```
Comment (christian-bromann) [inline lib/default-config.js:4]: Can this be documented?

**Review by christian-bromann — COMMENTED** [review]
One comment otherwise looks good to me.

File: lib/default-config.js (hunk 1 above)
Comment (ArminazK) [reply lib/default-config.js:4]: added some documentation

File: docs/API.md [hunk 2]
```diff
@@ -120,3 +120,8 @@ If you're getting this error, it means that you didn't shut down the server succ
 ```shell
 pkill -f selenium-standalone
 ```
+
+## set selenium-standalone version as node env parameter
```
Comment (christian-bromann) [inline docs/API.md:124]:
```suggestion
## Set `selenium-standalone` Version as NodeJS environment parameter
```

**Review by christian-bromann — APPROVED** [review]
Thank you 👍

File: docs/API.md [hunk 3]
```diff
@@ -120,3 +120,8 @@ If you're getting this error, it means that you didn't shut down the server succ
 ```shell
 pkill -f selenium-standalone
 ```
+
+## Set `selenium-standalone` Version as NodeJS environment parameter
+
+You can set any version by `process.env.SELENIUM_VERSION=3.141.59` before starting selenium-standalone  
+Default values are here: [lib/default-config.js](../lib/default-config.js)
```
Comment (christian-bromann) [inline docs/API.md:127]:
```suggestion
You can set any version by `process.env.SELENIUM_VERSION=3.141.59` before starting selenium-standalone. Default values are here: [lib/default-config.js](../lib/default-config.js)
```
